name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: hseeberger/scala-sbt:11.0.8_1.3.13_2.12.12

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.sbt ~/.m2 ~/.ivy2 ~/.cache
        key: ${{ runner.os }}-build-${{ hashFiles('build.sbt', 'api/build.sbt', 'ingest/build.sbt', 'core/build.sbt', 'project/Deps.scala') }}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run tests
      run: sbt test
